Fix building error due to CPP syntax error.
When building pax-britannica, gcc 5.2.1 complains about a syntax error in
minlua.c:

    gcc -Wall -O2 -DMEMARRAY_USE_OPENGL -DDOKIDOKI_LINUX -pthread
        -DEXTRA_LOADERS="../extra_loaders.h" -I/usr/include/lua5.1
        -c -o minlua.o minlua.c
    minlua.c: In function ‘init_preloaders’:
    minlua.c:45:14: error: #include expects "FILENAME" or <FILENAME>
        #include EXTRA_LOADERS
                 ^
    <builtin>: recipe for target 'minlua.o' failed

This commit fixes this error.